package com.alliedtech.lollibotapp;

public enum RobotCommand {
    COMMAND_MOVE_LINES,
    COMMAND_BATTERY_STATUS,
    COMMAND_ROBOT_STATUS,
    COMMAND_UPDATE_SCHEDULE,
    COMMAND_REMOVE_SCHEDULE,
    COMMAND_SET_LINE_COUNT,
    COMMAND_MOVE_TO_MIDDLE,
    COMMAND_MOVE_FROM_MIDDLE
}
